config/routes.rb
Rails.application.routes.draw do
  get "rooms/show"
  get "messages/show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about" => "homes#about"
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  devise_for :users
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    collection do
      get "search", to: "books#search", as: :search
    end
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get "search" => "users#search"
    member do
      get :followings, :followers
    end
    resource :relation_ships, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: "search"
  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]
  resources :groups do
    member do
      get "new_group_email" # メールフォーム表示
      post "send_group_email" # メール送信処理
      get "email_sent" # 送信完了画面
    end
  end
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end
  resources :notifications, only: [:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def is_owned_by?(user)
    owner.id == user.id
  end

  def get_group_image
    if group_image.attached?
      group_image
    else
      "no_image.jpg"
    end
  end

  def include_user?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.owner_id = current_user.id
    if group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    group = Group.find(params[:id])
    if group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def new_group_email
    @group = Group.find(params[:id])
  end

  def send_group_email
    @group = Group.find(params[:id])
    @owner = current_user
    @title = params[:title]
    @content = params[:content]

    # メール送信
    GroupMailer.group_notification(@group, @owner, @title, @content).deliver_now

    # 送信完了画面に遷移
    redirect_to email_sent_group_path(@group, title: @title, content: @content)
  end

  def email_sent
    @group = Group.find(params[:id])
    @title = params[:title]
    @content = params[:content]
  end

  private
    def group_params
      params.require(:group).permit(:name, :introduction, :group_image)
    end

    def ensure_correct_user
      @group = Group.find(params[:id])
      unless @group.owner_id == current_user.id
        redirect_to groups_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group, local: true do |f| %>

  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :group_image, class: "form-control-file", accept: "image/*" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>

<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td><%= image_tag group.get_group_image, size: "50x50" %></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= group.introduction %></td>
      <td><%= group.users.count %></td>
      <% if group.is_owned_by?(current_user) %>
        <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-success" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Group</h2>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/email_sent.html.erb
<h1>メール送信完了</h1>
<p>以下の内容でメールを送信しました。</p>
<h2>件名: <%= @title %></h2>
<p><%= @content %></p>
<%= link_to 'グループページに戻る', group_path(@group), class: 'btn btn-secondary' %>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>
      <h2 class="mt-3">New Book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= render 'index', groups: @groups %>
    </div>

  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>New Group</h3>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_group_email.html.erb
<h1><%= @group.name %> グループメール送信</h1>
<%= form_with url: send_group_email_group_path(@group), method: :post, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title, '件名' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, '内容' %>
    <%= f.text_area :content, class: 'form-control', rows: 5 %>
  </div>
  <%= f.submit '送信', class: 'btn btn-primary' %>
<% end %>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New Book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image, size: "50x50" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
                <% @group.users.each do |user| %>
                  <li style="list-style:none;"><%= user.name %></li>
                <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %>
              <% else %>
                <% if @group.include_user?(current_user) %>
                  <%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "Join this group", group_group_users_path(@group), method: :post, class: "btn btn-success" %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to 'Notice an Event', new_group_email_group_path(@group), class: 'btn btn-primary' %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>