config/routes.rb
Rails.application.routes.draw do
  get "rooms/show"
  get "messages/show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about" => "homes#about"
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  devise_for :users
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    collection do
      get "search", to: "books#search", as: :search
    end
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get "search" => "users#search"
    member do
      get :followings, :followers
    end
    resource :relation_ships, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: "search"
  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]
  resources :groups do
    member do
      get "new_group_email" # メールフォーム表示
      post "send_group_email" # メール送信処理
      get "email_sent" # 送信完了画面
    end
  end
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end
  resources :notifications, only: [:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :relation_ships, foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relation_ships, source: :followed
  has_many :reverse_of_relationships, class_name: "RelationShip", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no_image.jpg"
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    current_entry = Entry.where(user_id: current_user.id)
    another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      current_entry.each do |current|
        another_entry.each do |another|
          if current.room_id == another.room_id then
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    if params[:sort] == "star"
      @books = @user.books.order(star: :desc)
    else
      @books = @user.books.order(created_at: :desc)
    end
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @two_days_ago_book = @books.created_two_days_ago
    @three_days_ago_book = @books.created_three_days_ago
    @four_days_ago_book = @books.created_four_days_ago
    @five_days_ago_book = @books.created_five_days_ago
    @six_days_ago_book = @books.created_six_days_ago
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(["created_at LIKE ? ", "#{create_at}%"]).count
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = current_user
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def ensure_correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
    end

    def ensure_guest_user
      @user = User.find(params[:id])
      if @user.email == "guest@example.com"
        redirect_to user_path(current_user), notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
      end
    end
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td>
          <% if current_user.id != user.id %>
            <% if user.is_followed_by?(current_user) %>
              <%= link_to "フォロー外す", user_relation_ships_path(user), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relation_ships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, followings_user_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user) %></th>
  </tr>
  <tr>
    <td>
      <% if current_user.id != user.id %>
        <% if user.is_followed_by?(current_user) %>
          <%= link_to "フォロー外す", user_relation_ships_path(user), method: :delete, class: "btn btn-secondary btn-danger" %>
        <% else %>
          <%= link_to "フォローする", user_relation_ships_path(user), method: :post, class: "btn btn-secondary btn-success" %>
        <% end %>
      <% end %>
    </td>
    <td>
      <% unless user.id == current_user.id %>
        <% if (current_user.is_followed_by? user) && (user.is_followed_by? current_user) %>
          <% if is_room %>
            <%= link_to "DMを送る", room_path(room_id), class: "btn btn-secondary btn-success" %>
          <% else %>
            <%= form_for room do |f| %>
              <%= fields_for entry do |e| %>
                <%= e.hidden_field :user_id, value: user.id %>
              <% end %>
              <%= f.submit "DMをはじめる", class:"btn btn-primary btn-sm" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

<div class='row'>
  <% if current_user.id == user.id && user.email != "guest@example.com" %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.count == 0 %>
  <p>ユーザーはいません</p>
<% else %>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/followings.html.erb
<h2>Follow Users</h2>
<% if @users.count == 0 %>
  <p>ユーザーはいません</p>
<% else %>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %>｜<%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, is_room: @is_room, room: @room, entry: @entry, room_id: @room_id %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", user_path(@user, sort: "new") %> ｜ 
      <%= link_to "評価の高い順", user_path(@user, sort: "star") %>
      <%= render 'books/index',books: @books %>

      <h3>投稿数の前日比・前週比</h3>
      <%= render 'books/statistics_table',
      today_book: @today_book,
      yesterday_book: @yesterday_book,
      this_week_book: @this_week_book,
      last_week_book: @last_week_book %>

      <h3>７日間分の投稿数</h3>
      <%= render 'books/posts_per_week',
      six_days_ago_book: @six_days_ago_book,
      five_days_ago_book: @five_days_ago_book,
      four_days_ago_book: @four_days_ago_book,
      three_days_ago_book: @three_days_ago_book,
      two_days_ago_book: @two_days_ago_book,
      yesterday_book: @yesterday_book,
      today_book: @today_book %>

      <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>