config/routes.rb
Rails.application.routes.draw do
  get "rooms/show"
  get "messages/show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about" => "homes#about"
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  devise_for :users
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    collection do
      get "search", to: "books#search", as: :search
    end
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    get "search" => "users#search"
    member do
      get :followings, :followers
    end
    resource :relation_ships, only: [:create, :destroy]
  end
  get "search" => "searches#search", as: "search"
  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]
  resources :groups do
    member do
      get "new_group_email" # メールフォーム表示
      post "send_group_email" # メール送信処理
      get "email_sent" # 送信完了画面
    end
  end
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end
  resources :notifications, only: [:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :tag, presence: true
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_two_days_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_three_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_four_days_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_five_days_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_six_days_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @booknew = Book.new
    @post_comment = PostComment.new
    current_entry = Entry.where(user_id: current_user.id)
    another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      current_entry.each do |current|
        another_entry.each do |another|
          if current.room_id == another.room_id then
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      if @is_room
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorites).sort_by { |book| -book.favorites.where(created_at: from...to).count }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    user = @book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search
    @books = Book.where("tag LIKE ?", "%#{params[:tag]}%")
  end


  private
    def book_params
      params.require(:book).permit(:title, :body, :star, :tag)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>件のerrorが発生しました
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag, "タグ" %>
    <%= f.text_field :tag, class: 'form-control' %>
  </div>
  <% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {  
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: book %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to (book.user) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.tag, search_books_path(tag: book.tag) %></td>
        <td id="favorite_btn_<%= book.id %>">
          <%= render 'favorites/btn', book: book%>
        </td>
        <td>
          <%= "コメント数: #{book.post_comments.count}" %>
        </td>
        <td><%= render "books/static_rate", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_posts_per_week.html.erb
<table class="table table-bordered">
        <thead>
          <tr>
            <th>６日前</th>
            <th>５日前</th>
            <th>４日前</th>
            <th>３日前</th>
            <th>２日前</th>
            <th>１日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= six_days_ago_book.count %></td>
            <td><%= five_days_ago_book.count %></td>
            <td><%= four_days_ago_book.count %></td>
            <td><%= three_days_ago_book.count %></td>
            <td><%= two_days_ago_book.count %></td>
            <td><%= yesterday_book.count %></td>
            <td><%= today_book.count %></td>
          </tr>
        </tbody>
      </table>

      <canvas id="myLineChart"></canvas>
      <script>
        $(document).on('turbolinks:load', function() {
          var ctx = document.getElementById("myLineChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
              datasets: [
                {
                  label: '投稿した本の数',
                  data: [
                    <%= six_days_ago_book.count %>,
                    <%= five_days_ago_book.count %>,
                    <%= four_days_ago_book.count %>,
                    <%= three_days_ago_book.count %>,
                    <%= two_days_ago_book.count %>,
                    <%= yesterday_book.count %>,
                    <%= today_book.count %>
                  ],
                  borderColor: "rgba(0,0,255,1)",
                  backgroundColor: "rgba(0,0,0,0)",
                  tension: 0.5
                }
              ],
            },
            options: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              responsive: true,
              scales: {
                y:{
                  suggestedMin: 0,
                  suggestedMax: 10
                },
              },
            }
          });
        });
      </script>

app/views/books/_static_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= book.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/books/_statistics_table.html.erb
<table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿</th>
            <th>昨日の投稿</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= today_book.count %></td>
            <td><%= yesterday_book.count %></td>
            <% if yesterday_book.count == 0 %>
              <td>前日の投稿はなし</td>
            <% else %>
              <td><% the_day_before =   today_book.count / yesterday_book.count.to_f %>
              <%= (the_day_before * 100).round %>%</td>
            <% end %>
          </tr>
        </tbody>
      </table>
        
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿</th>
            <th>先週の投稿</th>
            <th>先週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= this_week_book.count %></td>
            <td><%= last_week_book.count %></td>
            <% if last_week_book.count == 0 %>
              <td>先週の投稿はなし</td>
            <% else %>
              <td><% the_week_before = this_week_book.count / last_week_book.count.to_f %>
              <%= (the_week_before * 100).round %>%</td>
            <% end %>
          </tr>
        </tbody>
      </table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books Index</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<h1>タグ検索結果: <%= params[:tag] %></h1>

<% if @books.present? %>
  <%= render 'books/index', books: @books %>
<% else %>
  <p>該当する投稿はありません。</p>
<% end %>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user, is_room: @is_room, room: @room, entry: @entry, room_id: @room_id %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.tag, search_books_path(tag: @book.tag) %></td>
          <td id="favorite_btn_<%= @book.id %>">
            <%= render 'favorites/btn', book: @book %>
          </td>
          <td id="comment_counter">
            <%= render 'post_comments/comment_count', book: @book %>
          </td>
          <td><%= render "static_rate", book: @book %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
        <div id="comment_index">
          <%= render 'post_comments/index', book: @book %>
        </div>
      <div>
        <%= render 'post_comments/new_comment', book: @book, post_comment: @post_comment %>
      </div>
    </div>
  </div>
</div>